package ru.fss.integration.ws.rpu.recipient.v01;

import org.springframework.context.annotation.Bean;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.0
 * 2021-05-18T14:58:21.493+03:00
 * Generated source version: 3.2.0
 * 
 */
@WebServiceClient(name = "RecipientServicePorts", 
                  wsdlLocation = "http://172.24.98.143:4080/ws-recipient-rpu/api/soap/RecipientServicePorts?wsdl",
                  targetNamespace = "http://www.fss.ru/integration/ws/rpu/Recipient/v01")
public class RecipientServicePorts extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.fss.ru/integration/ws/rpu/Recipient/v01", "RecipientServicePorts");
    public final static QName RecipientServicePortV01 = new QName("http://www.fss.ru/integration/ws/rpu/Recipient/v01", "RecipientServicePort_v01");
    static {
        URL url = null;
        try {
            url = new URL("http://172.24.98.143:4080/ws-recipient-rpu/api/soap/RecipientServicePorts?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(RecipientServicePorts.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://172.24.98.143:4080/ws-recipient-rpu/api/soap/RecipientServicePorts?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public RecipientServicePorts(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public RecipientServicePorts(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RecipientServicePorts() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public RecipientServicePorts(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public RecipientServicePorts(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public RecipientServicePorts(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns RecipientService
     */
    @WebEndpoint(name = "RecipientServicePort_v01")
    public RecipientService getRecipientServicePortV01() {
        return super.getPort(RecipientServicePortV01, RecipientService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RecipientService
     */
    @WebEndpoint(name = "RecipientServicePort_v01")
    public RecipientService getRecipientServicePortV01(WebServiceFeature... features) {
        return super.getPort(RecipientServicePortV01, RecipientService.class, features);
    }

}
