
package ru.fss.integration.ws.fault.v01;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.0
 * 2021-05-18T14:58:21.459+03:00
 * Generated source version: 3.2.0
 */

@WebFault(name = "internalFault", targetNamespace = "http://www.fss.ru/integration/types/fault/v01")
public class InternalException extends Exception {
    
    private ru.fss.integration.types.fault.v01.InternalFault internalFault;

    public InternalException() {
        super();
    }
    
    public InternalException(String message) {
        super(message);
    }
    
    public InternalException(String message, Throwable cause) {
        super(message, cause);
    }

    public InternalException(String message, ru.fss.integration.types.fault.v01.InternalFault internalFault) {
        super(message);
        this.internalFault = internalFault;
    }

    public InternalException(String message, ru.fss.integration.types.fault.v01.InternalFault internalFault, Throwable cause) {
        super(message, cause);
        this.internalFault = internalFault;
    }

    public ru.fss.integration.types.fault.v01.InternalFault getFaultInfo() {
        return this.internalFault;
    }
}
